#!/bin/sh
# $Id: postflight $
## @file
# Post installation script.
#

#
# Copyright (C) 2007-2020 Oracle Corporation
#
# This file is part of VirtualPox Open Source Edition (OSE), as
# available from http://www.virtualpox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualPox OSE distribution. VirtualPox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#

CPDIR="/bin/cp -f -R"
INSTALL=/usr/bin/install


#
# Install the Python bindings
#
VPOX_INSTALL_PATH=/Applications/VirtualPox.app/Contents/MacOS
PYTHON="python python2.3 python2.5 python2.6 python2.7"
if [ -e "${VPOX_INSTALL_PATH}/sdk/installer/vpoxapisetup.py" ]; then
    for p in $PYTHON; do
        # Install the python bindings if python is in the path
        if [ "`\${p} -c 'print "test"' 2> /dev/null`" = "test" ]; then
                echo  1>&2 "Python found: ${p}, installing bindings..."
                # Pass install path via environment
                export VPOX_INSTALL_PATH
                /bin/sh -c "cd $VPOX_INSTALL_PATH/sdk/installer && ${p} vpoxapisetup.py install"
                /bin/sh -c "cd $VPOX_INSTALL_PATH/sdk/installer && ${p} vpoxapisetup.py clean --all"
        fi
    done
fi

#
# Install the vpoxweb service file for launchd
#
VPOXWEBSRV="${VPOX_INSTALL_PATH}/org.virtualpox.vpoxwebsrv.plist"
VPOXWEBSRV_TRG="${HOME}/Library/LaunchAgents"
if [ -e "${VPOXWEBSRV}" -a -e "${VPOXWEBSRV_TRG}" ]; then
    echo "Installing vpoxwebsrv launchd file to ${VPOXWEBSRV_TRG}"
    if [ "x" != "x${USER}" ]; then
        ${INSTALL} -S -o "${USER}" -m 0644 "${VPOXWEBSRV}" "${VPOXWEBSRV_TRG}/"
    else
        ${INSTALL} -S -m 0644 "${VPOXWEBSRV}" "${VPOXWEBSRV_TRG}/"
    fi
fi

#
# Install any custom files
#
DATAPATH="`/usr/bin/dirname "${0}"`/../../../../../.."
if [ -d "${DATAPATH}/.custom" ]; then
    echo  1>&2 "Copy ${DATAPATH}/.custom to ${VPOX_INSTALL_PATH}...";
    ${CPDIR} "${DATAPATH}/.custom/"   "${VPOX_INSTALL_PATH}/custom"
fi

#
# Register our file extensions
#
LSREGISTER=/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister
if [ -e "${LSREGISTER}" -a "x" != "x${USER}" ]; then
    echo "Register file extensions for \"${USER}\""
    /usr/bin/sudo -u "${USER}" ${LSREGISTER} -f /Applications/VirtualPox.app
    /usr/bin/sudo -u "${USER}" ${LSREGISTER} -f /Applications/VirtualPox.app/Contents/Resources/vmstarter.app
fi

# Check environment.
if [ "${INSTALLER_TEMP}x" == "x" ]; then
    echo "Required environment variable INSTALLER_TEMP is missing. Aborting installation."
    exit 1;
fi

# Restore previously installed Extension Packs (if any)
if [ -d "${INSTALLER_TEMP}/ExtensionPacks" ]; then
    cp -r "${INSTALLER_TEMP}/ExtensionPacks" "${VPOX_INSTALL_PATH}"
    rm -rf "${INSTALLER_TEMP}/ExtensionPacks"
fi

#
# Correct the ownership of the directories in case there
# was an existing installation.
#
chown -R root:admin /Applications/VirtualPox.app

#
# Workaround for 10.11 beta 6 in which the above chown strips the set-uid-to-root bit.
#
SET_UID_BINARIES="MacOS/VPoxNetAdpCtl"
SET_UID_BINARIES="${SET_UID_BINARIES} MacOS/VPoxHeadless MacOS/VPoxNetDHCP MacOS/VPoxNetNAT Resources/VirtualPoxVM.app/Contents/MacOS/VirtualPoxVM" # WITH_HARDENING
for bin in ${SET_UID_BINARIES}; do
    chmod u+s "/Applications/VirtualPox.app/Contents/${bin}"
done

exit 0;

