# $Id: Makefile.kmk $
## @file
# Sub-Makefile for VPoxGL OpenGL state tracker.
#

#
# Copyright (C) 2018-2020 Oracle Corporation
#
# This file is part of VirtualPox Open Source Edition (OSE), as
# available from http://www.virtualpox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualPox OSE distribution. VirtualPox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#

SUB_DEPTH = ../../../../../..
include $(KBUILD_PATH)/subheader.kmk

# Define this to build software OpenGL driver
#VPOX_WITH_MESA3D_GL_SOFTWARE = 1

DLLS       += VPoxGL
DLLS.amd64 += VPoxGL-x86

VPoxGL_TEMPLATE = VPoxMesa3DGuestR3DllMinVista
# -wd4005: '__useHeader' : redefinition
VPoxGL_CFLAGS   = -wd4005
VPoxGL_INCS     = \
	$(VPOX_PATH_3D)/win/include \
	$(VPOX_PATH_MESA)/include/GL \
	$(VPOX_PATH_MESA)/src/gallium/state_trackers/wgl \
	$(VPOX_PATH_MESA)/src/gallium/winsys/sw \
	$(VPOX_PATH_MESA)/src/gallium/drivers \
	$(PATH_ROOT)/src/VPox/Additions/WINNT/Graphics/Video \
	$(PATH_ROOT)/src/VPox/Runtime/common/table \
	$(VPOX_PATH_VMSVGA_INC) \
	$(VPOX_GRAPHICS_INCS)
VPoxGL_SOURCES  = \
	$(VPOX_PATH_MESA)/src/gallium/state_trackers/wgl/opengl32.def \
	VPoxGL.rc
ifndef VPOX_WITH_MESA3D_GL_SOFTWARE
VPoxGL_SOURCES += \
	GaDrvEnvKMT.cpp \
	VPoxGL.c
else
VPoxGL_SOURCES += \
	$(VPOX_PATH_MESA)/src/gallium/targets/libgl-gdi/libgl_gdi.c
VPoxGL_SOURCES += \
	$(VPOX_PATH_MESA)/src/gallium/winsys/sw/gdi/gdi_sw_winsys.c
VPoxGL_SOURCES += \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_buffer.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_clear.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_context.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_compute.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_draw_arrays.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_fence.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_flush.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_fs_exec.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_image.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_prim_vbuf.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_quad_blend.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_quad_depth_test.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_quad_fs.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_quad_pipe.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_quad_stipple.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_query.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_screen.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_setup.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_state_blend.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_state_clip.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_state_derived.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_state_image.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_state_rasterizer.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_state_sampler.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_state_shader.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_state_so.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_state_surface.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_state_vertex.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_surface.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_tex_sample.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_tex_tile_cache.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_texture.c \
	$(VPOX_PATH_MESA)/src/gallium/drivers/softpipe/sp_tile_cache.c
endif
VPoxGL_LIBS     = \
	$(VPOX_PATH_ADDITIONS_LIB)/VPoxWddmUmHlp$(VPOX_SUFF_LIB) \
	$(VPOX_PATH_ADDITIONS_LIB)/VPoxMesaGalliumAuxLib$(VPOX_SUFF_LIB) \
	$(VPOX_PATH_ADDITIONS_LIB)/VPoxMesaWglLib$(VPOX_SUFF_LIB) \
	$(VPOX_PATH_ADDITIONS_LIB)/VPoxMesaUtilLib$(VPOX_SUFF_LIB) \
	$(VPOX_PATH_ADDITIONS_LIB)/VPoxMesaLib$(VPOX_SUFF_LIB)

ifdef VPOX_SIGN_ADDITIONS
 VPoxGL_INSTTYPE       = none
 VPoxGL_DEBUG_INSTTYPE = both
endif

#
# VPoxGL-x86 - x86 version of VPoxGL built for amd64 build
#
VPoxGL-x86_EXTENDS      = VPoxGL
VPoxGL-x86_BLD_TRG_ARCH = x86
VPoxGL-x86_LIBS         = \
	$(VPOX_PATH_ADDITIONS_LIB)/VPoxWddmUmHlp-x86$(VPOX_SUFF_LIB) \
	$(VPOX_PATH_ADDITIONS_LIB)/VPoxMesaGalliumAuxLib-x86$(VPOX_SUFF_LIB) \
	$(VPOX_PATH_ADDITIONS_LIB)/VPoxMesaWglLib-x86$(VPOX_SUFF_LIB) \
	$(VPOX_PATH_ADDITIONS_LIB)/VPoxMesaUtilLib-x86$(VPOX_SUFF_LIB) \
	$(VPOX_PATH_ADDITIONS_LIB)/VPoxMesaLib-x86$(VPOX_SUFF_LIB)
VPoxGL-x86_DEFS         = $(VPoxGL_DEFS) VPOX_WOW64

include $(FILE_KBUILD_SUB_FOOTER)

