#!/bin/sh
## @file
# VPoxService wrapper script.
#
# Load required kernel extensions before start service (if necessary).
#

#
# Copyright (C) 2007-2020 Oracle Corporation
#
# This file is part of VirtualPox Open Source Edition (OSE), as
# available from http://www.virtualpox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualPox OSE distribution. VirtualPox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#

export PATH="/bin:/usr/bin:/sbin:/usr/sbin:$PATH"

echo "Check if kernel extensions loaded..."
items="VPoxGuest"
for item in $items; do
    kext_item="org.virtualpox.kext.$item"
    loaded=`kextstat | grep $kext_item`
    if [ -z "$loaded" ] ; then
        echo "Loading $item kernel extension..."
        XNU_VERSION=`LC_ALL=C uname -r | LC_ALL=C cut -d . -f 1`
        if [ "$XNU_VERSION" -ge "10" ]; then
            kextutil /Library/Extensions/$item.kext
        else
            kextload /Library/Extensions/$item.kext
        fi
    fi
done

exec "/Library/Application Support/VirtualPox Guest Additions/VPoxService" -f

