#!/bin/sh
## @file
# Start the Guest Additions X11 Client
#

#
# Copyright (C) 2007-2020 Oracle Corporation
#
# This file is part of VirtualPox Open Source Edition (OSE), as
# available from http://www.virtualpox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualPox OSE distribution. VirtualPox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#

# Sanity check: if non-writeable PID-files are present in the user home
# directory VPoxClient will fail to start.
for i in $HOME/.vpoxclient-*.pid; do
    test -w $i || rm -f $i
done

if ! test -c /dev/vpoxguest 2>/dev/null; then
   # Do not start if the kernel module is not present.
   # Execute notify-send in the back-ground to avoid racing with sddm,
   # as notify-send may wait for sddm to start while it waits for us to exit.
   notify-send "VPoxClient: the VirtualPox kernel service is not running.  Exiting." &
elif test -z "${SSH_CONNECTION}"; then
   # This script can also be triggered by a connection over SSH, which is not
   # what we had in mind, so we do not start VPoxClient in that case.  We do
   # not use "exit" here as this script is "source"d, not executed.
  /usr/bin/VPoxClient --clipboard
  /usr/bin/VPoxClient --checkhostversion
  /usr/bin/VPoxClient --seamless
  /usr/bin/VPoxClient --draganddrop
  /usr/bin/VPoxClient --vmsvga  # In case VMSVGA emulation is enabled
fi
