#!/bin/sh
# $Id: postrm $
## @file
# VirtualPox post remove.
#

#
# Copyright (C) 2006-2019 Oracle Corporation
#
# This file is part of VirtualPox Open Source Edition (OSE), as
# available from http://www.virtualpox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualPox OSE distribution. VirtualPox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#

# we can be called with the following arguments (6.5 of Debian policy):
#  remove:            (our version): remove our package
#  purge:             (our version): purge our package
#  upgrade:           (our version): upgrade to a new version
#  failed-upgrade     (old version): failed to upgrade to a new version
#  abort-install      (our version): aborted install
#  abort-upgrade      (old version): aborted upgrade

if [ "$1" = "purge" -a ! -f /etc/init.d/vpoxdrv ] ; then
  update-rc.d vpoxdrv remove >/dev/null || exit $?
fi
if [ "$1" = "purge" -a ! -f /etc/init.d/vpoxnet ] ; then
  update-rc.d vpoxnet remove >/dev/null || exit $?
fi
if [ "$1" = "purge" -a ! -f /etc/init.d/vpoxweb-service ] ; then
  update-rc.d vpoxweb-service remove >/dev/null || exit $?
fi
if [ "$1" = "purge" -a ! -f /etc/init.d/vpoxballoonctrl-service ] ; then
  update-rc.d vpoxballoonctrl-service remove >/dev/null || exit $?
fi

# remove installed extension packs
if [ "$1" = "purge" ]; then
  rm -rf /usr/lib/virtualpox/ExtensionPacks/*
fi

#DEBHELPER#

exit 0
