#!/bin/bash
# $Id: preinst $
## @file
# VirtualPox pre-install.
#

#
# Copyright (C) 2006-2019 Oracle Corporation
#
# This file is part of VirtualPox Open Source Edition (OSE), as
# available from http://www.virtualpox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualPox OSE distribution. VirtualPox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#

# we can be called with the following arguments (6.5 of Debian policy):
#  install:          (our version): install our version
#  upgrade:          (our version): upgrade to our version
#  abort-upgrade:    (old version): upgrade to a new version failed

# defaults
[ -r /etc/default/virtualpox ] && . /etc/default/virtualpox

if [ "$1" = "install" -o "$1" = "upgrade" ]; then

  . /usr/share/debconf/confmodule
  db_version 2.0
  db_capb backup

  # check for old installation
  if [ -r /etc/vpox/vpox.cfg ]; then
    . /etc/vpox/vpox.cfg
    if [ "x$INSTALL_DIR" != "x" -a -d "$INSTALL_DIR" ]; then
      db_fset virtualpox/old-installation-found seen false || true
      db_input critical virtualpox/old-installation-found || true
      db_go || true
      exit 1
    fi
    # we will remove that file in postinst
  fi

  # check for active VMs
  # Execute the installed package's pre-uninstaller if present.
  /usr/lib/virtualpox/prerm-common.sh 2>/dev/null || true
  # Stop services from older versions without pre-uninstaller.
  invoke-rc.d vpoxballoonctrl-service stop 2>/dev/null || true
  /etc/init.d/vpoxballoonctrl-service stop 2>/dev/null || true
  invoke-rc.d vpoxautostart-service stop 2>/dev/null || true
  /etc/init.d/vpoxautostart-service stop 2>/dev/null || true
  invoke-rc.d vpoxweb-service stop 2>/dev/null || true
  /etc/init.d/vpoxweb-service stop 2>/dev/null || true
  VPOXSVC_PID=`pidof VPoxSVC 2>/dev/null || true`
  if [ -n "$VPOXSVC_PID" ]; then
    # ask the daemon to terminate immediately
    kill -USR1 $VPOXSVC_PID
    sleep 1
    if pidof VPoxSVC > /dev/null 2>&1; then
      db_fset virtualpox/old-running seen false || true
      db_input critical virtualpox/old-running || true
      db_go || true
      exit 1
    fi
  fi

fi # "$1" = "install" -o "$1" = "upgrade"

#DEBHELPER#

