# $Id: Makefile.kmk $
## @file
# Makefile for D3D test application.
#

#
# Copyright (C) 2017-2020 Oracle Corporation
#
# This file is part of VirtualPox Open Source Edition (OSE), as
# available from http://www.virtualpox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualPox OSE distribution. VirtualPox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#

SUB_DEPTH = ../../../../../../../../../..
include $(KBUILD_PATH)/subheader.kmk

PROGRAMS += VPoxGaD3DTest
VPoxGaD3DTest_TEMPLATE    = VPOXR3STATIC
VPoxGaD3DTest_SDKS        = ReorderCompilerIncs $(VPOX_WINDDK)
VPoxGaD3DTest_DEFS        = D3DTEST_STANDALONE
VPoxGaD3DTest_LIBS        = d3d9.lib
VPoxGaD3DTest_SOURCES     = \
	d3d9main.cpp \
	d3d9render.cpp \
	d3dhlp.cpp

#
# 32-bit version of VPoxGaD3DTest.
#
PROGRAMS.amd64 += VPoxGaD3DTest-x86
VPoxGaD3DTest-x86_EXTENDS = VPoxGaD3DTest
VPoxGaD3DTest-x86_BLD_TRG_ARCH = x86

include $(FILE_KBUILD_SUB_FOOTER)
