#!/bin/sh
# $Id: files_vpoxsf $
## @file
# Shared file between Makefile.kmk and export_modules.sh.
#

#
# Copyright (C) 2007-2020 Oracle Corporation
#
# This file is part of VirtualPox Open Source Edition (OSE), as
# available from http://www.virtualpox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualPox OSE distribution. VirtualPox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#

FILES_VPOXSF_NOBIN=" \
    ${PATH_ROOT}/include/iprt/nocrt/limits.h=>include/iprt/nocrt/limits.h \
    ${PATH_ROOT}/include/iprt/alloc.h=>include/iprt/alloc.h \
    ${PATH_ROOT}/include/iprt/asm.h=>include/iprt/asm.h \
    ${PATH_ROOT}/include/iprt/asm-amd64-x86.h=>include/iprt/asm-amd64-x86.h \
    ${PATH_ROOT}/include/iprt/asm-math.h=>include/iprt/asm-math.h \
    ${PATH_ROOT}/include/iprt/assert.h=>include/iprt/assert.h \
    ${PATH_ROOT}/include/iprt/assertcompile.h=>include/iprt/assertcompile.h \
    ${PATH_ROOT}/include/iprt/cdefs.h=>include/iprt/cdefs.h \
    ${PATH_ROOT}/include/iprt/err.h=>include/iprt/err.h \
    ${PATH_ROOT}/include/iprt/errcore.h=>include/iprt/errcore.h \
    ${PATH_ROOT}/include/iprt/fs.h=>include/iprt/fs.h \
    ${PATH_ROOT}/include/iprt/latin1.h=>include/iprt/latin1.h \
    ${PATH_ROOT}/include/iprt/list.h=>include/iprt/list.h \
    ${PATH_ROOT}/include/iprt/log.h=>include/iprt/log.h \
    ${PATH_ROOT}/include/iprt/mangling.h=>include/iprt/mangling.h \
    ${PATH_ROOT}/include/iprt/mem.h=>include/iprt/mem.h \
    ${PATH_ROOT}/include/iprt/param.h=>include/iprt/param.h \
    ${PATH_ROOT}/include/iprt/path.h=>include/iprt/path.h \
    ${PATH_ROOT}/include/iprt/semaphore.h=>include/iprt/semaphore.h \
    ${PATH_ROOT}/include/iprt/stdarg.h=>include/iprt/stdarg.h \
    ${PATH_ROOT}/include/iprt/stdint.h=>include/iprt/stdint.h \
    ${PATH_ROOT}/include/iprt/string.h=>include/iprt/string.h \
    ${PATH_ROOT}/include/iprt/time.h=>include/iprt/time.h \
    ${PATH_ROOT}/include/iprt/types.h=>include/iprt/types.h \
    ${PATH_ROOT}/include/iprt/uint64.h=>include/iprt/uint64.h \
    ${PATH_ROOT}/include/iprt/uni.h=>include/iprt/uni.h \
    ${PATH_ROOT}/include/iprt/utf16.h=>include/iprt/utf16.h \
    ${PATH_ROOT}/include/iprt/linux/version.h=>include/iprt/linux/version.h \
    ${PATH_ROOT}/include/VPox/cdefs.h=>include/VPox/cdefs.h \
    ${PATH_ROOT}/include/VPox/err.h=>include/VPox/err.h \
    ${PATH_ROOT}/include/VPox/log.h=>include/VPox/log.h \
    ${PATH_ROOT}/include/VPox/ostypes.h=>include/VPox/ostypes.h \
    ${PATH_ROOT}/include/VPox/param.h=>include/VPox/param.h \
    ${PATH_ROOT}/include/VPox/shflsvc.h=>include/VPox/shflsvc.h \
    ${PATH_ROOT}/include/VPox/types.h=>include/VPox/types.h \
    ${PATH_ROOT}/include/VPox/VPoxGuest.h=>include/VPox/VPoxGuest.h \
    ${PATH_ROOT}/include/VPox/VPoxGuestCoreTypes.h=>include/VPox/VPoxGuestCoreTypes.h \
    ${PATH_ROOT}/include/VPox/VPoxGuestLib.h=>include/VPox/VPoxGuestLib.h \
    ${PATH_ROOT}/include/VPox/VPoxGuestLibSharedFolders.h=>include/VPox/VPoxGuestLibSharedFolders.h \
    ${PATH_ROOT}/include/VPox/VPoxGuestLibSharedFoldersInline.h=>include/VPox/VPoxGuestLibSharedFoldersInline.h \
    ${PATH_ROOT}/include/VPox/VPoxGuestMangling.h=>include/VPox/VPoxGuestMangling.h \
    ${PATH_ROOT}/include/VPox/VMMDev.h=>include/VPox/VMMDev.h \
    ${PATH_ROOT}/include/VPox/VMMDevCoreTypes.h=>include/VPox/VMMDevCoreTypes.h \
    ${PATH_ROOT}/src/VPox/Additions/common/VPoxGuest/lib/VPoxGuestR0LibInternal.h=>VPoxGuestR0LibInternal.h \
    ${PATH_ROOT}/src/VPox/Additions/common/VPoxGuest/lib/VPoxGuestR0LibGenericRequest.cpp=>VPoxGuestR0LibGenericRequest.c \
    ${PATH_ROOT}/src/VPox/Additions/common/VPoxGuest/lib/VPoxGuestR0LibHGCM.cpp=>VPoxGuestR0LibHGCM.c \
    ${PATH_ROOT}/src/VPox/Additions/common/VPoxGuest/lib/VPoxGuestR0LibIdc.cpp=>VPoxGuestR0LibIdc.c \
    ${PATH_ROOT}/src/VPox/Additions/common/VPoxGuest/lib/VPoxGuestR0LibIdc-unix.cpp=>VPoxGuestR0LibIdc-unix.c \
    ${PATH_ROOT}/src/VPox/Additions/common/VPoxGuest/lib/VPoxGuestR0LibInit.cpp=>VPoxGuestR0LibInit.c \
    ${PATH_ROOT}/src/VPox/Additions/common/VPoxGuest/lib/VPoxGuestR0LibPhysHeap.cpp=>VPoxGuestR0LibPhysHeap.c \
    ${PATH_ROOT}/src/VPox/Additions/common/VPoxGuest/lib/VPoxGuestR0LibSharedFolders.c=>VPoxGuestR0LibSharedFolders.c \
    ${PATH_ROOT}/src/VPox/Installer/linux/Makefile-header.gmk=>Makefile-header.gmk \
    ${PATH_ROOT}/src/VPox/Installer/linux/Makefile-footer.gmk=>Makefile-footer.gmk \
    ${PATH_ROOT}/src/VPox/Runtime/common/math/gcc/divdi3.c=>divdi3.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/math/gcc/moddi3.c=>moddi3.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/math/gcc/qdivrem.c=>qdivrem.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/math/gcc/quad.h=>quad.h \
    ${PATH_ROOT}/src/VPox/Runtime/common/math/gcc/udivdi3.c=>udivdi3.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/math/gcc/udivmoddi4.c=>udivmoddi4.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/math/gcc/umoddi3.c=>umoddi3.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/the-linux-kernel.h=>r0drv/linux/the-linux-kernel.h \
    ${PATH_ROOT}/src/VPox/Additions/linux/sharedfolders/Makefile.module=>Makefile \
    ${PATH_ROOT}/src/VPox/Additions/linux/sharedfolders/dirops.c=>dirops.c \
    ${PATH_ROOT}/src/VPox/Additions/linux/sharedfolders/lnkops.c=>lnkops.c \
    ${PATH_ROOT}/src/VPox/Additions/linux/sharedfolders/regops.c=>regops.c \
    ${PATH_ROOT}/src/VPox/Additions/linux/sharedfolders/utils.c=>utils.c \
    ${PATH_ROOT}/src/VPox/Additions/linux/sharedfolders/vbsfmount.h=>vbsfmount.h \
    ${PATH_ROOT}/src/VPox/Additions/linux/sharedfolders/vfsmod.c=>vfsmod.c \
    ${PATH_ROOT}/src/VPox/Additions/linux/sharedfolders/vfsmod.h=>vfsmod.h \
    ${PATH_OUT}/version-generated.h=>version-generated.h \
    ${PATH_OUT}/revision-generated.h=>revision-generated.h \
    ${PATH_OUT}/product-generated.h=>product-generated.h \
"

FILES_VPOXSF_BIN=" \
"
