#!/bin/sh
# $Id: files_vpoxvideo_drm $
## @file
# Shared file between Makefile.kmk and export_modules.sh.
#

#
# Copyright (C) 2007-2020 Oracle Corporation
#
# This file is part of VirtualPox Open Source Edition (OSE), as
# available from http://www.virtualpox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualPox OSE distribution. VirtualPox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#

FILES_VPOXVIDEO_DRM_NOBIN=" \
    ${PATH_ROOT}/src/VPox/Additions/freebsd/drm/vpoxvideo_drm.c=>vpoxvideo_drm.c \
    ${PATH_ROOT}/src/VPox/Additions/freebsd/drm/Makefile=>Makefile \
"

FILES_VPOXVIDEO_DRM_BIN=" \
"
