#!/bin/sh
# $Id: files_vpoxdrv $
## @file
# Shared file between Makefile.kmk and export_modules.sh.
#

#
# Copyright (C) 2007-2020 Oracle Corporation
#
# This file is part of VirtualPox Open Source Edition (OSE), as
# available from http://www.virtualpox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualPox OSE distribution. VirtualPox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#
# The contents of this file may alternatively be used under the terms
# of the Common Development and Distribution License Version 1.0
# (CDDL) only, as it comes in the "COPYING.CDDL" file of the
# VirtualPox OSE distribution, in which case the provisions of the
# CDDL are applicable instead of those of the GPL.
#
# You may elect to license modified versions of this file under the
# terms and conditions of either the GPL or the CDDL or both.
#

FILES_VPOXDRV_NOBIN=" \
    ${PATH_ROOT}/include/iprt/alloc.h=>include/iprt/alloc.h \
    ${PATH_ROOT}/include/iprt/asm.h=>include/iprt/asm.h \
    ${PATH_ROOT}/include/iprt/asm-amd64-x86.h=>include/iprt/asm-amd64-x86.h \
    ${PATH_ROOT}/include/iprt/asm-math.h=>include/iprt/asm-math.h \
    ${PATH_ROOT}/include/iprt/assert.h=>include/iprt/assert.h \
    ${PATH_ROOT}/include/iprt/assertcompile.h=>include/iprt/assertcompile.h \
    ${PATH_ROOT}/include/iprt/avl.h=>include/iprt/avl.h \
    ${PATH_ROOT}/include/iprt/cdefs.h=>include/iprt/cdefs.h \
    ${PATH_ROOT}/include/iprt/cpuset.h=>include/iprt/cpuset.h \
    ${PATH_ROOT}/include/iprt/crc.h=>include/iprt/crc.h \
    ${PATH_ROOT}/include/iprt/ctype.h=>include/iprt/ctype.h \
    ${PATH_ROOT}/include/iprt/err.h=>include/iprt/err.h \
    ${PATH_ROOT}/include/iprt/errcore.h=>include/iprt/errcore.h \
    ${PATH_ROOT}/include/iprt/errno.h=>include/iprt/errno.h \
    ${PATH_ROOT}/include/iprt/heap.h=>include/iprt/heap.h \
    ${PATH_ROOT}/include/iprt/handletable.h=>include/iprt/handletable.h \
    ${PATH_ROOT}/include/iprt/initterm.h=>include/iprt/initterm.h \
    ${PATH_ROOT}/include/iprt/latin1.h=>include/iprt/latin1.h \
    ${PATH_ROOT}/include/iprt/list.h=>include/iprt/list.h \
    ${PATH_ROOT}/include/iprt/lockvalidator.h=>include/iprt/lockvalidator.h \
    ${PATH_ROOT}/include/iprt/log.h=>include/iprt/log.h \
    ${PATH_ROOT}/include/iprt/mangling.h=>include/iprt/mangling.h \
    ${PATH_ROOT}/include/iprt/mem.h=>include/iprt/mem.h \
    ${PATH_ROOT}/include/iprt/memobj.h=>include/iprt/memobj.h \
    ${PATH_ROOT}/include/iprt/mp.h=>include/iprt/mp.h \
    ${PATH_ROOT}/include/iprt/net.h=>include/iprt/net.h \
    ${PATH_ROOT}/include/iprt/param.h=>include/iprt/param.h \
    ${PATH_ROOT}/include/iprt/path.h=>include/iprt/path.h \
    ${PATH_ROOT}/include/iprt/power.h=>include/iprt/power.h \
    ${PATH_ROOT}/include/iprt/process.h=>include/iprt/process.h \
    ${PATH_ROOT}/include/iprt/rand.h=>include/iprt/rand.h \
    ${PATH_ROOT}/include/iprt/semaphore.h=>include/iprt/semaphore.h \
    ${PATH_ROOT}/include/iprt/spinlock.h=>include/iprt/spinlock.h \
    ${PATH_ROOT}/include/iprt/stdarg.h=>include/iprt/stdarg.h \
    ${PATH_ROOT}/include/iprt/stdint.h=>include/iprt/stdint.h \
    ${PATH_ROOT}/include/iprt/string.h=>include/iprt/string.h \
    ${PATH_ROOT}/include/iprt/thread.h=>include/iprt/thread.h \
    ${PATH_ROOT}/include/iprt/time.h=>include/iprt/time.h \
    ${PATH_ROOT}/include/iprt/timer.h=>include/iprt/timer.h \
    ${PATH_ROOT}/include/iprt/types.h=>include/iprt/types.h \
    ${PATH_ROOT}/include/iprt/uint128.h=>include/iprt/uint128.h \
    ${PATH_ROOT}/include/iprt/uint64.h=>include/iprt/uint64.h \
    ${PATH_ROOT}/include/iprt/uni.h=>include/iprt/uni.h \
    ${PATH_ROOT}/include/iprt/utf16.h=>include/iprt/utf16.h \
    ${PATH_ROOT}/include/iprt/uuid.h=>include/iprt/uuid.h \
    ${PATH_ROOT}/include/iprt/x86.h=>include/iprt/x86.h \
    ${PATH_ROOT}/include/iprt/linux/version.h=>include/iprt/linux/version.h \
    ${PATH_ROOT}/include/iprt/nocrt/limits.h=>include/iprt/nocrt/limits.h \
    ${PATH_ROOT}/include/VPox/cdefs.h=>include/VPox/cdefs.h \
    ${PATH_ROOT}/include/VPox/err.h=>include/VPox/err.h \
    ${PATH_ROOT}/include/VPox/log.h=>include/VPox/log.h \
    ${PATH_ROOT}/include/VPox/param.h=>include/VPox/param.h \
    ${PATH_ROOT}/include/VPox/sup.h=>include/VPox/sup.h \
    ${PATH_ROOT}/include/VPox/types.h=>include/VPox/types.h \
    ${PATH_ROOT}/include/VPox/SUPDrvMangling.h=>include/VPox/SUPDrvMangling.h \
    ${PATH_ROOT}/include/VPox/VPoxTpG.h=>include/VPox/VPoxTpG.h \
    ${PATH_ROOT}/include/VPox/vmm/hm_vmx.h=>include/VPox/vmm/hm_vmx.h \
    ${PATH_ROOT}/include/VPox/vmm/hm_svm.h=>include/VPox/vmm/hm_svm.h \
    ${PATH_ROOT}/src/VPox/HostDrivers/Support/linux/SUPDrv-linux.c=>linux/SUPDrv-linux.c \
    ${PATH_ROOT}/src/VPox/HostDrivers/Support/SUPDrv.cpp=>SUPDrv.c \
    ${PATH_ROOT}/src/VPox/HostDrivers/Support/SUPDrvGip.cpp=>SUPDrvGip.c \
    ${PATH_ROOT}/src/VPox/HostDrivers/Support/SUPDrvSem.cpp=>SUPDrvSem.c \
    ${PATH_ROOT}/src/VPox/HostDrivers/Support/SUPDrvTracer.cpp=>SUPDrvTracer.c \
    ${PATH_ROOT}/src/VPox/HostDrivers/Support/SUPDrv-dtrace.cpp=>SUPDrvDTrace.c \
    ${PATH_ROOT}/src/VPox/HostDrivers/Support/SUPDrvIDC.h=>SUPDrvIDC.h \
    ${PATH_ROOT}/src/VPox/HostDrivers/Support/SUPDrvIOC.h=>SUPDrvIOC.h \
    ${PATH_ROOT}/src/VPox/HostDrivers/Support/SUPDrvInternal.h=>SUPDrvInternal.h \
    ${PATH_ROOT}/src/VPox/HostDrivers/Support/SUPLibAll.cpp=>SUPLibAll.c \
    ${PATH_ROOT}/src/VPox/Installer/linux/Makefile-footer.gmk=>Makefile-footer.gmk \
    ${PATH_ROOT}/src/VPox/Installer/linux/Makefile-header.gmk=>Makefile-header.gmk \
    ${PATH_ROOT}/src/VPox/Runtime/common/alloc/alloc.cpp=>common/alloc/alloc.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/alloc/heapsimple.cpp=>common/alloc/heapsimple.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/checksum/crc32.cpp=>common/checksum/crc32.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/checksum/ipv4.cpp=>common/checksum/ipv4.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/checksum/ipv6.cpp=>common/checksum/ipv6.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/err/RTErrConvertFromErrno.cpp=>common/err/RTErrConvertFromErrno.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/err/RTErrConvertToErrno.cpp=>common/err/RTErrConvertToErrno.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/err/errinfo.cpp=>common/err/errinfo.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/log/log.cpp=>common/log/log.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/log/logellipsis.cpp=>common/log/logellipsis.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/log/logrel.cpp=>common/log/logrel.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/log/logrelellipsis.cpp=>common/log/logrelellipsis.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/log/logcom.cpp=>common/log/logcom.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/log/logformat.cpp=>common/log/logformat.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/math/gcc/divdi3.c=>math/gcc/divdi3.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/math/gcc/divmoddi4.c=>math/gcc/divmoddi4.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/math/gcc/moddi3.c=>math/gcc/moddi3.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/math/gcc/qdivrem.c=>math/gcc/qdivrem.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/math/gcc/quad.h=>math/gcc/quad.h \
    ${PATH_ROOT}/src/VPox/Runtime/common/math/gcc/udivdi3.c=>math/gcc/udivdi3.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/math/gcc/udivmoddi4.c=>math/gcc/udivmoddi4.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/math/gcc/umoddi3.c=>math/gcc/umoddi3.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/misc/RTAssertMsg1Weak.cpp=>common/misc/RTAssertMsg1Weak.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/misc/RTAssertMsg2.cpp=>common/misc/RTAssertMsg2.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/misc/RTAssertMsg2Add.cpp=>common/misc/RTAssertMsg2Add.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/misc/RTAssertMsg2AddWeak.cpp=>common/misc/RTAssertMsg2AddWeak.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/misc/RTAssertMsg2AddWeakV.cpp=>common/misc/RTAssertMsg2AddWeakV.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/misc/RTAssertMsg2Weak.cpp=>common/misc/RTAssertMsg2Weak.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/misc/RTAssertMsg2WeakV.cpp=>common/misc/RTAssertMsg2WeakV.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/misc/assert.cpp=>common/misc/assert.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/misc/handletable.cpp=>common/misc/handletable.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/misc/handletable.h=>common/misc/handletable.h \
    ${PATH_ROOT}/src/VPox/Runtime/common/misc/handletablectx.cpp=>common/misc/handletablectx.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/misc/thread.cpp=>common/misc/thread.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/string/RTStrCat.cpp=>common/string/RTStrCat.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/string/RTStrCopy.cpp=>common/string/RTStrCopy.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/string/RTStrCopyEx.cpp=>common/string/RTStrCopyEx.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/string/RTStrCopyP.cpp=>common/string/RTStrCopyP.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/string/RTStrNCmp.cpp=>common/string/RTStrNCmp.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/string/RTStrNLen.cpp=>common/string/RTStrNLen.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/string/stringalloc.cpp=>common/string/stringalloc.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/string/strformat.cpp=>common/string/strformat.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/string/RTStrFormat.cpp=>common/string/RTStrFormat.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/string/strformatnum.cpp=>common/string/strformatnum.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/string/strformatrt.cpp=>common/string/strformatrt.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/string/strformattype.cpp=>common/string/strformattype.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/string/strprintf.cpp=>common/string/strprintf.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/string/strprintf-ellipsis.cpp=>common/string/strprintf-ellipsis.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/string/strtonum.cpp=>common/string/strtonum.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/table/avlpv.cpp=>common/table/avlpv.c \
    ${PATH_ROOT}/src/VPox/Runtime/common/table/avl_Base.cpp.h=>common/table/avl_Base.cpp.h \
    ${PATH_ROOT}/src/VPox/Runtime/common/table/avl_Get.cpp.h=>common/table/avl_Get.cpp.h \
    ${PATH_ROOT}/src/VPox/Runtime/common/table/avl_GetBestFit.cpp.h=>common/table/avl_GetBestFit.cpp.h \
    ${PATH_ROOT}/src/VPox/Runtime/common/table/avl_RemoveBestFit.cpp.h=>common/table/avl_RemoveBestFit.cpp.h \
    ${PATH_ROOT}/src/VPox/Runtime/common/table/avl_DoWithAll.cpp.h=>common/table/avl_DoWithAll.cpp.h \
    ${PATH_ROOT}/src/VPox/Runtime/common/table/avl_Destroy.cpp.h=>common/table/avl_Destroy.cpp.h \
    ${PATH_ROOT}/src/VPox/Runtime/common/time/time.cpp=>common/time/time.c \
    ${PATH_ROOT}/src/VPox/Runtime/include/internal/assert.h=>include/internal/assert.h \
    ${PATH_ROOT}/src/VPox/Runtime/include/internal/initterm.h=>include/internal/initterm.h \
    ${PATH_ROOT}/src/VPox/Runtime/include/internal/iprt.h=>include/internal/iprt.h \
    ${PATH_ROOT}/src/VPox/Runtime/include/internal/lockvalidator.h=>include/internal/lockvalidator.h \
    ${PATH_ROOT}/src/VPox/Runtime/include/internal/magics.h=>include/internal/magics.h \
    ${PATH_ROOT}/src/VPox/Runtime/include/internal/mem.h=>include/internal/mem.h \
    ${PATH_ROOT}/src/VPox/Runtime/include/internal/memobj.h=>include/internal/memobj.h \
    ${PATH_ROOT}/src/VPox/Runtime/include/internal/string.h=>include/internal/string.h \
    ${PATH_ROOT}/src/VPox/Runtime/include/internal/sched.h=>include/internal/sched.h \
    ${PATH_ROOT}/src/VPox/Runtime/include/internal/process.h=>include/internal/process.h \
    ${PATH_ROOT}/src/VPox/Runtime/include/internal/thread.h=>include/internal/thread.h \
    ${PATH_ROOT}/src/VPox/Runtime/include/internal/time.h=>include/internal/time.h \
    ${PATH_ROOT}/src/VPox/Runtime/generic/RTAssertShouldPanic-generic.cpp=>generic/RTAssertShouldPanic-generic.c \
    ${PATH_ROOT}/src/VPox/Runtime/generic/RTLogWriteStdErr-stub-generic.cpp=>generic/RTLogWriteStdErr-stub-generic.c \
    ${PATH_ROOT}/src/VPox/Runtime/generic/RTLogWriteStdOut-stub-generic.cpp=>generic/RTLogWriteStdOut-stub-generic.c \
    ${PATH_ROOT}/src/VPox/Runtime/generic/RTLogWriteUser-generic.cpp=>generic/RTLogWriteUser-generic.c \
    ${PATH_ROOT}/src/VPox/Runtime/generic/RTMpGetArraySize-generic.cpp=>generic/RTMpGetArraySize-generic.c \
    ${PATH_ROOT}/src/VPox/Runtime/generic/RTMpGetCoreCount-generic.cpp=>generic/RTMpGetCoreCount-generic.c \
    ${PATH_ROOT}/src/VPox/Runtime/generic/RTSemEventWait-2-ex-generic.cpp=>generic/RTSemEventWait-2-ex-generic.c \
    ${PATH_ROOT}/src/VPox/Runtime/generic/RTSemEventWaitNoResume-2-ex-generic.cpp=>generic/RTSemEventWaitNoResume-2-ex-generic.c \
    ${PATH_ROOT}/src/VPox/Runtime/generic/RTSemEventMultiWait-2-ex-generic.cpp=>generic/RTSemEventMultiWait-2-ex-generic.c \
    ${PATH_ROOT}/src/VPox/Runtime/generic/RTSemEventMultiWaitNoResume-2-ex-generic.cpp=>generic/RTSemEventMultiWaitNoResume-2-ex-generic.c \
    ${PATH_ROOT}/src/VPox/Runtime/generic/RTTimerCreate-generic.cpp=>generic/RTTimerCreate-generic.c \
    ${PATH_ROOT}/src/VPox/Runtime/generic/errvars-generic.cpp=>generic/errvars-generic.c \
    ${PATH_ROOT}/src/VPox/Runtime/generic/mppresent-generic.cpp=>generic/mppresent-generic.c \
    ${PATH_ROOT}/src/VPox/Runtime/generic/uuid-generic.cpp=>generic/uuid-generic.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/alloc-r0drv.cpp=>r0drv/alloc-r0drv.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/alloc-r0drv.h=>r0drv/alloc-r0drv.h \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/initterm-r0drv.cpp=>r0drv/initterm-r0drv.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/mp-r0drv.h=>r0drv/mp-r0drv.h \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/mpnotification-r0drv.c=>r0drv/mpnotification-r0drv.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/power-r0drv.h=>r0drv/power-r0drv.h \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/powernotification-r0drv.c=>r0drv/powernotification-r0drv.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/rtStrFormatKernelAddress-r0drv-linux.c=>r0drv/linux/rtStrFormatKernelAddress-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/RTLogWriteDebugger-r0drv-linux.c=>r0drv/linux/RTLogWriteDebugger-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/assert-r0drv-linux.c=>r0drv/linux/assert-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/alloc-r0drv-linux.c=>r0drv/linux/alloc-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/initterm-r0drv-linux.c=>r0drv/linux/initterm-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/memobj-r0drv-linux.c=>r0drv/linux/memobj-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/memuserkernel-r0drv-linux.c=>r0drv/linux/memuserkernel-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/mp-r0drv-linux.c=>r0drv/linux/mp-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/mpnotification-r0drv-linux.c=>r0drv/linux/mpnotification-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/process-r0drv-linux.c=>r0drv/linux/process-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/semevent-r0drv-linux.c=>r0drv/linux/semevent-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/semeventmulti-r0drv-linux.c=>r0drv/linux/semeventmulti-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/semfastmutex-r0drv-linux.c=>r0drv/linux/semfastmutex-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/semmutex-r0drv-linux.c=>r0drv/linux/semmutex-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/spinlock-r0drv-linux.c=>r0drv/linux/spinlock-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/string.h=>r0drv/linux/string.h \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/the-linux-kernel.h=>r0drv/linux/the-linux-kernel.h \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/thread-r0drv-linux.c=>r0drv/linux/thread-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/thread2-r0drv-linux.c=>r0drv/linux/thread2-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/threadctxhooks-r0drv-linux.c=>r0drv/linux/threadctxhooks-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/time-r0drv-linux.c=>r0drv/linux/time-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/timer-r0drv-linux.c=>r0drv/linux/timer-r0drv-linux.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/linux/waitqueue-r0drv-linux.h=>r0drv/linux/waitqueue-r0drv-linux.h \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/generic/semspinmutex-r0drv-generic.c=>r0drv/generic/semspinmutex-r0drv-generic.c \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/generic/threadctxhooks-r0drv-generic.cpp=>r0drv/generic/threadctxhooks-r0drv-generic.cpp \
    ${PATH_ROOT}/src/VPox/Runtime/r0drv/memobj-r0drv.cpp=>r0drv/memobj-r0drv.c \
    ${PATH_ROOT}/src/VPox/Runtime/VPox/log-vpox.cpp=>VPox/log-vpox.c \
    ${PATH_OUT}/version-generated.h=>version-generated.h \
    ${PATH_OUT}/revision-generated.h=>revision-generated.h \
    ${PATH_OUT}/product-generated.h=>product-generated.h \
"

FILES_VPOXDRV_BIN=" \
"
