#!/bin/sh
# $Id: files_vpoxvideo_drv $
## @file
# Shared file between Makefile.kmk and export_modules.sh.
#

#
# Copyright (C) 2011-2020 Oracle Corporation
#
# This file is part of VirtualPox Open Source Edition (OSE), as
# available from http://www.virtualpox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualPox OSE distribution. VirtualPox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#

FILES_VPOXVIDEO_DRM_NOBIN=" \
    ${PATH_OUT}/version-generated.h=>version-generated.h \
    ${PATH_OUT}/revision-generated.h=>revision-generated.h \
    ${PATH_OUT}/product-generated.h=>product-generated.h \
    ${PATH_ROOT}/include/VPox/Graphics/VPoxVideo.h=>vpoxvideo.h \
    ${PATH_ROOT}/include/VPox/Graphics/VPoxVideoGuest.h=>vpoxvideo_guest.h \
    ${PATH_ROOT}/include/VPox/Graphics/HGSMIChannels.h=>hgsmi_channels.h \
    ${PATH_ROOT}/include/VPox/Graphics/HGSMIChSetup.h=>hgsmi_ch_setup.h \
    ${PATH_ROOT}/include/VPox/Graphics/HGSMIContext.h=>hgsmi_context.h \
    ${PATH_ROOT}/include/VPox/Graphics/HGSMIDefs.h=>hgsmi_defs.h \
    ${PATH_ROOT}/include/VPox/Graphics/VPoxVideoErr.h=>vpox_err.h \
    ${PATH_ROOT}/include/VPox/Graphics/VPoxVideoVBE.h=>vpoxvideo_vbe.h \
    ${PATH_ROOT}/src/VPox/Additions/common/VPoxVideo/HGSMIBase.cpp=>hgsmi_base.c \
    ${PATH_ROOT}/src/VPox/Additions/common/VPoxVideo/Modesetting.cpp=>modesetting.c \
    ${PATH_ROOT}/src/VPox/Additions/common/VPoxVideo/VBVABase.cpp=>vbva_base.c \
    ${PATH_ROOT}/src/VPox/Additions/linux/drm/vpox_drv.c=>vpox_drv.c \
    ${PATH_ROOT}/src/VPox/Additions/linux/drm/vpox_drv.h=>vpox_drv.h \
    ${PATH_ROOT}/src/VPox/Additions/linux/drm/vpox_fb.c=>vpox_fb.c \
    ${PATH_ROOT}/src/VPox/Additions/linux/drm/vpox_irq.c=>vpox_irq.c \
    ${PATH_ROOT}/src/VPox/Additions/linux/drm/vpox_main.c=>vpox_main.c \
    ${PATH_ROOT}/src/VPox/Additions/linux/drm/vpox_mode.c=>vpox_mode.c \
    ${PATH_ROOT}/src/VPox/Additions/linux/drm/vpox_prime.c=>vpox_prime.c \
    ${PATH_ROOT}/src/VPox/Additions/linux/drm/vpox_ttm.c=>vpox_ttm.c \
    ${PATH_ROOT}/src/VPox/Additions/linux/drm/vpox_hgsmi.c=>vpox_hgsmi.c \
    ${PATH_ROOT}/src/VPox/Installer/linux/Makefile-header.gmk=>Makefile-header.gmk \
    ${PATH_ROOT}/src/VPox/Installer/linux/Makefile-footer.gmk=>Makefile-footer.gmk \
    ${PATH_ROOT}/src/VPox/Additions/linux/drm/Makefile.module.kms=>Makefile \
"

FILES_VPOXVIDEO_DRM_BIN=" \
"
