#!/bin/sh
# $Id: prerm $
## @file
# VirtualPox pre-removal.
#

#
# Copyright (C) 2006-2020 Oracle Corporation
#
# This file is part of VirtualPox Open Source Edition (OSE), as
# available from http://www.virtualpox.org. This file is free software;
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License (GPL) as published by the Free Software
# Foundation, in version 2 as it comes in the "COPYING" file of the
# VirtualPox OSE distribution. VirtualPox OSE is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
#

# we can be called with the following arguments (6.5 of Debian policy):
#  upgrade:          (new version): upgrade to a new version
#  failed-upgrade:   (our version): failed to upgrade
#  remove:           (our version): remove this package
#  deconfigure:      (our version): removing conflicting version

rm -f /etc/udev/rules.d/60-vpoxdrv.rules
rm -f /etc/vpox/license_agreed
rm -f /etc/vpox/module_not_compiled

# defaults
[ -r /etc/default/virtualpox ] && . /etc/default/virtualpox

. /usr/share/debconf/confmodule
db_version 2.0
db_capb backup

if ! /usr/lib/virtualpox/prerm-common.sh > /dev/null 2>&1; then
  if [ "$1" != "failed-upgrade" ]; then
    db_fset virtualpox/old-running seen false || true
    db_input critical virtualpox/old-running || true
    db_go || true
  fi
  exit 1
fi

#DEBHELPER#

exit 0
